### ISSUE TITLE
Component: Pagination

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#138]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by X140hu4** [comment]
Hi, it's my first time working on a project on github and I still have quite a lot to learn so do not hesitate to tell me if I do something wrong.

I have started working on this issue. I realized I needed the button component from issue #127 and since the PR hasn't been merged yet I took the pieces I needed from that PR to write the pagination block, is that alright? Also I had to take out a `margin-bottom: 1rem;` on the button to have the elements aligned with flexbox.

Here is what I got so far: https://github.com/X140hu4/ConexionFelina/tree/Issue_138_Pagination

**Comment by Diphendara** [comment]
Hi! @X140hu4, if the issue is not finish you can make a Pull Request (PR) and add a comment like "it's not finish" then we can see the changes you have made, also once you finish the PR you can add a comment in the PR like "i'm finish this issue", we should download your proyect and check if all works fine, then we review your code with you in the PR.
